### PR TITLE
added translation files and description

### PR DESCRIPTION
**Pull request by tv-openbig**
translation template .pot for the module and german translation .po

### CODE REVIEW

**Comment by tv-openbig** [comment]
@hbrunn on modules translation i have seen that i fixed probably some "wording" in the translation file.
For example i have replaced Generic CSV by DATEV Format .csv. I assume we should fix that better already in the original terms. From the history i guess this modules concept was to plugin other (generic.csv) fomat types.

Another example is the menus name. I have "replaced" the origin name with the german term "DATEV Import".

Parent menu should also be [Invoicing/Accounting/Actions]
Currently it is [Invoicing/Accounting]


May we also add a default file format in the wizard (Generic CSV or in the future "DATEV format .csv")

**Comment by tv-openbig** [comment]
@hbrunn Am i right that Readme and the index.html under /static/description can be created automatically ?

**Comment by hbrunn** [comment]
thanks, and yes, I'll do that in the main PR

**Comment by tv-openbig** [comment]
@tv-openbig I have to do the same for the v16 PR, correct ?

**Comment by hbrunn** [comment]
I can cherry pick those commits too

**Pull request merged**
